<?

function webiz_campaign_menu(){
	$items = array();
	$items['campaign_pin'] = array(
		'title' => 'User register ',
		'description' => t("recieve video log"),
		'page callback' => 'webiz_campaign_pin_check',
		//'page arguments' => array(3),
		'type' => MENU_CALLBACK,
		'access callback' => TRUE
	);
	
	$items['campaign_register'] = array(
		'title' => 'Campaign register ',
		'description' => t("recieve video log"),
		'page callback' => 'webiz_campaign_register_page',
		//'page arguments' => array(3),
		'type' => MENU_CALLBACK,
		'access callback' => TRUE
	);
	$items['api/pincode_registered'] = array(
		'title' => 'Campaign register ',
		'description' => t("recieve video log"),
		'page callback' => 'webiz_campaign_pincode_registered',
		//'page arguments' => array(3),
		'type' => MENU_CALLBACK,
		'access callback' => TRUE
	);
	
	return $items;
}

function webiz_campaign_register_page() {
  //check pin
  global $base_url;
  $pincode = isset($_POST['pincode']) ? $_POST['pincode'] : '';
  $havesite = isset($_POST['havesite']) ? $_POST['havesite'] : '';
  $pinstat = webiz_campaign_pincode_isvalid($pincode);
  if($pincode && $pinstat == "VALID") {
    $iframe = "<br/>Your Pincode is $pincode<br/>";
    $iframe .= "<iframe frameborder=0 width='900' height='1000' src='http://webiz.co.th:8888/campaign_register?pincode=$pincode&havesite=$havesite&notheme=1&next=$base_url/api/pincode_registered'></iframe>";
    return $iframe;  
  } else {
    if($pinstat=="INVALID_CHECKSUM") $pincode_form = '<font color="red">Pincode is invalid</font>';
    elseif($pinstat=="NOT_FOUND") $pincode_form = '<font color="red">Pincode is not found</font>';
    elseif($pinstat=="REGISTERED") $pincode_form = '<font color="red">Pincode is already used</font>';
    $pincode_form .= "<form action='' method='post'>";
    $pincode_form .= "กรอก Pincode <br/> <input id='pincode' name='pincode' type='text'/ value=\"$pincode\"><br/>";
    $pincode_form .= "<input type='radio' name='havesite' value='1'";if($havesite==1) $pincode_form .= " checked";  $pincode_form .=">มีเว็บไซต์<br>";
    $pincode_form .= "<input type='radio' name='havesite' value='0'";if($havesite==0) $pincode_form .= " checked";  $pincode_form .=">ไม่มีเว็บไซต์<br>";
    $pincode_form .= "<input id='pincode' type='submit' value='รับสิทธิ์ประโยชน์'/>";
    $pincode_form .= "</form>";
    return $pincode_form;
  }
}

function webiz_campaign_pincode_isvalid($pincode){
  $length = strlen($pincode);$sum=0;
  for($i=0;$i<$length-1;$i++) {
    $sum += $pincode[$i] * ($i+1);
  }
  $exsum=$sum;
  $supexsum=0;
  while($exsum >= 10) {
     $supexsum = 0;
     $supexsum = $exsum%10 + $exsum/10%10 + $exsum/100%100;
    $exsum = $supexsum;
  }
  if($exsum!=$pincode[strlen($pincode)-1]) return "INVALID_CHECKSUM";
  $result = db_query("SELECT * FROM {webiz_campaign_pincode}  WHERE pincode = '%s'",$pincode);
  if($row = db_fetch_array($result)) {//registered
      if($row['registered']==0)
        return "VALID";
      else 
        return "REGISTERED";
  } else {
    return "NOT_FOUND";
  }
}

function webiz_campaign_pincode_registered(){
  if($_GET['pincode']) {
      db_query("UPDATE {webiz_campaign_pincode} SET registered=1 WHERE pincode = '%s'",$_GET['pincode']);
      echo 'true';
  } else
  echo 'false';exit;
}

